<!--
/**
 * Magenizr Debugger
 *
 * @copyright   Copyright (c) 2018 - 2022 Magenizr (https://www.magenizr.com)
 * @license     https://www.magenizr.com/license Magenizr EULA
 */
-->

<?php

$helper = $block->getHelper();
$types = ['log', 'report'];
$reportFile = $block->getFileSystem()->getLastReportFile();

?>

<div id="magenizr-debugger">

    <?php if ($helper->isAccessRestricted()): ?>
        <p><?= $escaper->escapeHtml(__('The access to this feature is restricted.')); ?></p>
    <?php else: ?>

        <?php if (!$helper->getScopeConfig('enabled')): ?>
            <p><?= $escaper->escapeHtmlAttr(__('The module is temporarily disabled. Go to <i>Stores > Configuration > Advanced > Developer > Debugger</i> and enable Debugger.')); ?></p>
        <?php else: ?>

            <div class="row">
                <div class="col-m-6">
                    <h2><?= $escaper->escapeHtml(__('Logs and Reports')); ?></h2>
                    <?php if ($helper->getScopeConfig('download_logs_reports_allow')): ?>
                        <ul>
                            <?php foreach ($types as $type): ?>
                                <li>
                                    <?php
                                        $details = $block->getFileSystem()->getDirDetails($type);
                                    if (empty($details)) { continue; }
                                    ?>

                                    <?php $link = $block->getUrl('magenizr_debugger/download/file', [
                                        '_current' => true,
                                        '_use_rewrite'=>true,
                                        '_query' => ['type' => $type]
                                    ]); ?>

                                    <?= __('<a href="%1">%2</a>', $link, $details['name']); ?>
                                    <?= __('(%1)', $details['size']); ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <p><?= $escaper->escapeHtml(__('This feature is disabled in the configurations.')); ?></p>
                    <?php endif; ?>

                </div>
                <div class="col-m-6">
                    <h2><?= $escaper->escapeHtml(__('PHP')); ?></h2>
                    <?php if ($helper->getScopeConfig('php_display_version')): ?>
                        <?= $escaper->escapeHtml($block->getPhp()->getPhpVersion()); ?>
                    <?php else: ?>
                        <p><?= $escaper->escapeHtml(__('This feature is disabled in the configurations.')); ?></p>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row">
                <div class="col-m-12">
                    <h2><?= $escaper->escapeHtml(__('Report')); ?></h2>
                    <?php if ($helper->getScopeConfig('report_display_latest')): ?>
                        <?php if ($reportFile): ?>
                            <p><?= __('Latest report file <strong>%1</strong> from <strong>%2</strong> located in ./var/report/.', $block->getBasename($reportFile), $block->getFileCTime($reportFile)) ?></p>

                            <textarea class=""><?= $escaper->escapeHtmlAttr($block->getFileSystem()->getLastReportFileContent()); ?></textarea>
                        <?php else: ?>
                            <p><?= $escaper->escapeHtmlAttr(__('There is no report file available.')); ?></p>
                        <?php endif; ?>
                    <?php else: ?>
                        <p><?= $escaper->escapeHtmlAttr(__('This feature is disabled in the configurations.')); ?></p>
                    <?php endif; ?>
                </div>
            </div>

        <?php endif; ?>
    <?php endif; ?>

</div>
