<!--
/**
 * Magenizr Debugger
 *
 * @category    Magenizr
 * @package     Magenizr_Debugger
 * @copyright   Copyright (c) 2018 Magenizr (http://www.magenizr.com)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
-->

<?php

$helper = $block->getHelper();
$types = ['log', 'report'];
$reportFile = $block->getFileSystem()->getLastReportFile();

?>

<div id="magenizr-debug">

    <?php if ($helper->isAccessRestricted()): ?>
        <p><?php echo __('The access to this feature is restricted.'); ?></p>
    <?php else: ?>

        <?php if (!$helper->getScopeConfig('enabled')): ?>
            <p><?php echo __('The module is temporarily disabled. Go to <i>Stores > Configuration > Advanced > Developer > Debugger</i> and enable Debugger.'); ?></p>
        <?php else: ?>

            <div class="row">
                <div class="col-m-6">
                    <h2><?php echo __('Logs and Reports'); ?></h2>
                    <?php if ($helper->getScopeConfig('download_logs_reports_allow')): ?>
                        <ul>
                            <?php foreach($types as $type) : ?>
                                <li>
                                    <?php
                                        $details = $block->getFileSystem()->getDirDetails($type);
                                        if (empty($details)) { continue; }
                                    ?>

                                    <?php $link = $block->getUrl('magenizr_debugger/download/file', [
                                        '_current' => true,
                                        '_use_rewrite'=>true,
                                        '_query' => ['type' => $type]
                                    ]); ?>

                                    <?php echo sprintf('<a href="%s">%s</a>', $link, $details['name']); ?>
                                    <?php echo __('(%1)', $details['size']); ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <p><?php echo __('This feature is disabled in the configurations.'); ?></p>
                    <?php endif; ?>

                </div>
                <div class="col-m-6">
                    <h2><?php echo __('PHP'); ?></h2>
                    <?php if ($helper->getScopeConfig('php_display_version')): ?>
                        <?php echo $block->getPhp()->getPhpVersion(); ?>
                    <?php else: ?>
                        <p><?php echo __('This feature is disabled in the configurations.'); ?></p>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row">
                <div class="col-m-12">
                    <h2><?php echo __('Report'); ?></h2>
                    <?php if ($helper->getScopeConfig('report_display_latest')): ?>
                        <?php if ($reportFile): ?>
                            <p><?php echo __('Latest report file <strong>%1</strong> from ./var/report/.', basename($reportFile)); ?></p>

                            <textarea class=""><?php echo $block->getFileSystem()->getLastReportFileContent(); ?></textarea>
                        <?php else: ?>
                            <p><?php echo __('There is no report file available.'); ?></p>
                        <?php endif; ?>
                    <?php else: ?>
                        <p><?php echo __('This feature is disabled in the configurations.'); ?></p>
                    <?php endif; ?>
                </div>
            </div>

        <?php endif; ?>
    <?php endif; ?>

</div>
