<!--
/**
 * Magenizr Debugger
 *
 * @category    Magenizr
 * @package     Magenizr_Debugger
 * @copyright   Copyright (c) 2018 Magenizr (http://www.magenizr.com)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
-->

<?php echo __('Follow us on'); ?> <a href="https://github.com/magenizr" target="_blank">GitHub</a>, <a href="https://twitter.com/magenizr" target="_blank">Twitter</a> and <a href="https://www.facebook.com/magenizr" target="_blank">Facebook</a>.
